### 新增用户
POST http://localhost:8080/user/add
Content-Type: application/json

{
  "username": "tom",
  "password": "123456",
  "name": "Tom",
  "email": "tom@test.com"
}

### 查询用户
GET http://localhost:8080/user/list

### 修改用户
PUT http://localhost:8080/user/update/1
Content-Type: application/json

{
  "username": "tom",
  "password": "123456",
  "name": "Tom-new",
  "email": "tom-new@test.com"
}

### 新增权限
POST http://localhost:8080/permission/add
Content-Type: application/json

{
  "code": "user:manage",
  "name": "用户管理",
  "description": "可以维护用户增删改查"
}

### 查询权限
GET http://localhost:8080/permission/list

### 给用户授权
POST http://localhost:8080/permission/grant?userId=1&permissionId=1

### 登录测试
POST http://localhost:8080/auth/login?username=tom&password=123456

### 查看登录状态
GET http://localhost:8080/auth/me

### 新增客服
POST http://localhost:8080/customer/add
Content-Type: application/json

{
  "name": "客服A",
  "status": "NORMAL"
}

### 创建会话
POST http://localhost:8080/session/create?userId=1&customerId=1

### HTTP 保存消息
POST http://localhost:8080/message/send?sessionId=1&senderId=1&senderType=USER&content=hello-http

### 查询消息
GET http://localhost:8080/message/list/1
