### 新增用户
POST http://localhost:8080/user/add
Content-Type: application/json

{
  "username": "admin",
  "password": "123456",
  "name": "管理员",
  "email": "admin@test.com"
}

### 查询用户
GET http://localhost:8080/user/list

### 新增角色
POST http://localhost:8080/role/add
Content-Type: application/json

{
  "roleName": "管理员",
  "roleCode": "admin",
  "remark": "管理后台"
}

### 查询角色
GET http://localhost:8080/role/list

### 新增权限
POST http://localhost:8080/permission/add
Content-Type: application/json

{
  "permissionName": "新增用户",
  "permissionCode": "user:add",
  "remark": "用户新增"
}

### 查询权限
GET http://localhost:8080/permission/list

### 用户绑定角色
POST http://localhost:8080/auth-relation/user-role?userId=1&roleId=1

### 角色绑定权限
POST http://localhost:8080/auth-relation/role-permission?roleId=1&permissionId=1

### 登录
POST http://localhost:8080/auth/login?username=admin&password=123456

### 检查权限
GET http://localhost:8080/auth/check?permission=user:add
